name: Functional Android App Tests

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
    pull_request_target:

jobs:
    android-app:
        runs-on: ubuntu-latest
        # Src: https://hugo.alliau.me/posts/2021-05-04-migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets.html#share-your-secrets-with-dependabot
        # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
        # Otherwise, clone it normally.
        if: |
            github.event_name == 'pull_request' ||
            (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
        steps:
            - name: ⬇️ Checkout Repository
              if: ${{ github.event_name != 'pull_request_target' }}
              uses: actions/checkout@v4

            - name: ⬇️ Checkout PR Repository
              if: ${{ github.event_name == 'pull_request_target' }}
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: 🟢 Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"

            - name: 🧩 Install Dependencies
              run: npm ci

            - name: 🔍 Lint
              run: npm run lint
