name: Functional iOS App Tests

on:
    workflow_dispatch:
    pull_request:
    pull_request_target:

jobs:
    ios-app:
        runs-on: ubuntu-latest
        # Only run the job if the PR is not created by the dependabot, the dependabot is only used in combination with Android
        if: github.actor != 'dependabot[bot]' && github.event_name == 'pull_request'
        steps:
            - name: ⬇️ Checkout Repository
              uses: actions/checkout@v6

            - name: 🟢 Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version-file: ".nvmrc"

            - name: 🧩 Install Dependencies
              run: npm ci

            - name: 🔍 Lint
              run: npm run lint
